[build]
  command = "yarn run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "20.9.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20.9.2" }

[dev]
  command = "yarn run dev"
  publish = "build"
  port = 5173
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; style-src 'self' https://rsms.me 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
